# Generated by Django 5.2.6 on 2025-09-04 20:01

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('lyrics', models.TextField(blank=True, help_text='Suggested Lyrics')),
                ('is_fan_chant', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Background or story behind the song')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('media_type', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('SPOTIFY', 'Spotify'), ('SOUNDCLOUD', 'SoundCloud'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='song.song')),
            ],
        ),
    ]
