# Generated by Django 5.2.6 on 2026-06-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_club_players"),
        ("player", "0001_initial"),
        ("song", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs",
                to="club.club",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs",
                to="player.player",
            ),
        ),
    ]
