# Generated by Django 5.2.6 on 2026-06-17 20:13

from django.db import migrations, models


def copy_club_fk_to_m2m(apps, schema_editor):
    Song = apps.get_model("song", "Song")
    for song in Song.objects.exclude(club_id=None):
        song.clubs.add(song.club_id)


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_club_players"),
        ("song", "0002_song_club_song_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="clubs",
            field=models.ManyToManyField(
                blank=True, related_name="songs", to="club.club"
            ),
        ),
        migrations.RunPython(copy_club_fk_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="song",
            name="club",
        ),
    ]
