# Generated by Django 5.2.6 on 2026-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="players",
            field=models.ManyToManyField(
                blank=True, related_name="clubs", to="player.player"
            ),
        ),
    ]
