# Generated by Django 5.2.6 on 2026-06-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_club_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="primary_color",
            field=models.CharField(
                blank=True,
                help_text="Primary brand color as hex (e.g. #C8102E).",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="secondary_color",
            field=models.CharField(
                blank=True,
                help_text="Secondary brand color as hex (e.g. #FFFFFF).",
                max_length=7,
            ),
        ),
    ]
