# Generated by Django 5.2.6 on 2026-06-18 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chant", "0001_initial"),
        ("song", "0003_song_clubs_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes", models.CharField(max_length=50)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chants",
                        to="chant.match",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chants",
                        to="song.song",
                    ),
                ),
            ],
            options={
                "ordering": ("match", "minutes"),
            },
        ),
    ]
